app1/urls.py
from django.contrib import admin
from django.urls import path
from .views import ajouter, ajoumariage, ajoudeces, rechercher_persone, rechercher_mariage, recherche_deces, edit, update, venue_pdf, extrait_pdf, extrait_mariage, extrait_deces, statistique


urlpatterns = [
   
    path('ajouter/', ajouter, name='ajouter'), 
    path('ajoumariage/', ajoumariage, name='ajoumariage'),
    path('ajoudeces/', ajoudeces, name='ajoudeces'),
    path('rechercher_persone/', rechercher_persone, name='rechercher_persone'),
    path('rechercher_mariage/', rechercher_mariage, name='rechercher_mariage'),
    path('rechercher_deces/', recherche_deces, name='rechercher_deces'),
    path('edit/<int:id>/', edit, name='edit'),
    path('update/<int:id>/', update, name='update'),
    path('venue_pdf/', venue_pdf, name='venue_pdf'),
    path('extrait_pdf/<int:id>/', extrait_pdf, name='extrait_pdf'),
    path('extrait_mariage/<int:id>/', extrait_mariage, name='extrait_mariage'),
    path('extrait_deces/<int:id>/', extrait_deces, name='extrait_deces'),
    path('statistique/', statistique, name='statistique'),
]

projet/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('acounts.urls')),
]

app1/models.py
from django.db import models
import datetime



class Wilaya(models.Model):
    NomW = models.CharField(max_length=50, verbose_name="Wilaya ")
    CodePostalW = models.CharField(max_length=5, verbose_name="Code Postal")
    

    #def __unicode__(self):
     #   return self.libelle_wilaya
    class Meta:
        ordering = ['NomW']

    def __str__(self):
        return f"{self.NomW }"


class Daira(models.Model):
    NomD = models.CharField(max_length=50, verbose_name="Daira de Naissance")
    CodePostalD = models.CharField(max_length=5, verbose_name="Code Postal")
    Wilaya = models.ForeignKey(Wilaya, verbose_name='Wilaya', on_delete=models.CASCADE)

    #def __unicode__(self):
     #   return self.libelle_daira
    class Meta:
        ordering = ['NomD']

    def __str__(self):
        return f"{self.NomD}"

class Commune(models.Model):
    NomC= models.CharField(max_length=50, verbose_name="Commune de Naissance")
    CodePostalC = models.CharField(max_length=5, verbose_name="Code Postal")
    Daira = models.ForeignKey(Daira, verbose_name='Daira', on_delete=models.CASCADE)

    #def __unicode__(self):
     #   return self.libelle_commune
    class Meta:
        ordering = ['NomC']

    def __str__(self):
        return f"{self.NomC }"

class BuretatCivile(models.Model):
    libelle_betat = models.CharField(max_length=200, verbose_name="Bureau d'etat Civil")
    Commune = models.ForeignKey(Commune, verbose_name='Commune', on_delete=models.CASCADE)

    #def __unicode__(self):
        #   return self.libelle_betat
    class Meta:
        ordering = ['libelle_betat']

    def __str__(self):
        return f"{self.libelle_betat }"



class Persone(models.Model):

    Sexe = (
        ('Masculin', 'Masculin'),
        ('Feminin', 'Feminin'),
    )
    nom = models.CharField(max_length=250, verbose_name='Nom')
    prenoms = models.CharField(max_length=250, verbose_name='Prenoms')
    sexe = models.CharField(max_length=150, verbose_name='sexe', choices=Sexe)
    date_naiss = models.DateField(verbose_name='Date de Naissance')
    heure_naiss = models.TimeField(verbose_name='Heure de Naissance')
    pere = models.ForeignKey('self', verbose_name='Nom et Prénoms du Pere', on_delete=models.CASCADE, blank=True, null=True, related_name='peres')
    pere_pere = models.ForeignKey('self', verbose_name='Nom et Prénoms du Pere du Pere', on_delete=models.CASCADE, blank=True, null=True, related_name='peres_pere')
    mere = models.ForeignKey('self', verbose_name='Nom et Prénoms du Mere', on_delete=models.CASCADE, blank=True, null=True, related_name='meres')
    pere_mere = models.ForeignKey('self', verbose_name='Nom et Prénoms du Pere du Mere', on_delete=models.CASCADE, blank=True, null=True, related_name='meres_mere')
    lieun  = models.ForeignKey(Commune, verbose_name='Lieu de Naissance', on_delete=models.CASCADE)
    BuretatCivile = models.ForeignKey(BuretatCivile, verbose_name='Bureau d etat Civil', on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = "Personne"
        verbose_name = "Acte de naissance"
        ordering = ['nom', 'prenoms']
   

    def __str__(self):
        return f"{self.nom} {self.prenoms}" 

class Homme(models.Model):
    nom = models.CharField(max_length=30, verbose_name="Nom l homme")
    prenoms = models.CharField(max_length=30, verbose_name="Prenoms de homme")
    date_naiss = models.DateField(verbose_name='Date de Naissance')

    class Meta:
        verbose_name_plural = "Homme"
        verbose_name = "Homme"
    def __str__(self):
        return f"{self.nom} {self.prenoms}" 

class Femme(models.Model):
    nom = models.CharField(max_length=30, verbose_name="Nom la Femme")
    prenoms = models.CharField(max_length=30, verbose_name="Prenoms de la Femme")
    date_naiss = models.DateField(verbose_name='Date de Naissance')

    class Meta:
        verbose_name_plural = "Femme"
        verbose_name = "Femme"
    def __str__(self):
        return f"{self.nom} {self.prenoms} " 



class Mariage(models.Model):
    
    marie = models.ForeignKey(Homme, verbose_name="Nom et Prenoms du Marie(e)", on_delete=models.CASCADE, related_name='marie')
    profession_marie = models.CharField(max_length=50, verbose_name="Profession du Marie(e)")
    domicile   = models.CharField(max_length=50, verbose_name="Lieu de Domicile du Marie(e)")
   
    mariee = models.ForeignKey(Femme, verbose_name="Nom et Prenoms du CONJOINT(E)", on_delete=models.CASCADE, related_name='conjoint')
    profession_mariee = models.CharField(max_length=50, verbose_name="Profession du CONJOINT(E)")
    
    date_mariage = models.DateField(verbose_name="Date du Mariage")
    heure_mariage = models.TimeField(verbose_name="Heure du Mariage")
    lieu_mariage = models.CharField(max_length=50, verbose_name="Lieu de Celebartion du Mariage")
    BuretatCivile = models.ForeignKey(BuretatCivile, verbose_name='Bureau d etat Civil', on_delete=models.CASCADE)
    temoine1 = models.ForeignKey(Homme, verbose_name="Nom et Prenoms du Temoin 1", on_delete=models.CASCADE, related_name='temoin1')
    temoine2 = models.ForeignKey(Homme, verbose_name="Nom et Prenoms du Temoin 2", on_delete=models.CASCADE, related_name='temoin2')


    class Meta:
        verbose_name_plural = "Actes de Mariage"
        verbose_name = "Acte de Mariage"
    def __str__(self):
        return f"{self.marie} {self.mariee}" 




class Deces(models.Model):
    personedeces = models.OneToOneField(Persone, verbose_name="Nom et Prenoms du Decede", on_delete=models.PROTECT, related_name='deces')
    annonceur = models.OneToOneField(Persone, verbose_name="Nom et Prenoms d", on_delete=models.PROTECT, related_name='annonceur')
    date_deces = models.DateField(verbose_name="Date du Deces")
    heure_deces = models.TimeField(verbose_name="Heure du Deces")
    lieu_deces = models.CharField(max_length=500, verbose_name="Lieu du Deces")
    cause_deces = models.CharField(max_length=500, verbose_name="Cause du Deces")

    class Meta:
        verbose_name_plural = "Actes de Deces"
        verbose_name = "Acte de Deces"

    def __str__(self):
        return f"{self. personedeces} "    









app1/views.py
from django.shortcuts import render, redirect
from .forms import PersoneForm , MariageForm, DecesForm
from .models import Persone, Mariage, Deces, Homme, Femme
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import datetime



# Create your views here.
def extrait_deces(request, id):
    buf = io.BytesIO()
    # Create a canvas 
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 12)

   
    # add line to texte 
    
    
    deces = Deces.objects.get(id=id)
    
    
    # add text object to canvas
    c.drawString(130, 40, "République Algérienne Démocratique et Populaire") 
    c.drawString(30, 70, "Ministère de l'Intérieur et des Collectivités Locales")
    c.drawString(30, 90, "Direction de l'Etat Civil")
    c.drawString(30, 110, "Willaya:   "+(deces.personedeces.BuretatCivile.Commune.Daira.Wilaya).__str__())
    c.drawString(50,111, "............................................................") 
    c.drawString(30, 130, "Daira:   "+(deces.personedeces.BuretatCivile.Commune.Daira).__str__())
    c.drawString(50,131, "............................................................") 
    c.drawString(30, 150, "Commune:   "+(deces.personedeces.BuretatCivile.Commune).__str__()) 
    c.drawString(50,151, "............................................................")
    c.drawString(30, 170, "Bureau:   "+(deces.personedeces.BuretatCivile).__str__())
    c.drawString(50,171, "............................................................")
    c.drawString(240, 220, "ACTE DE DECES")
    c.drawString(148,260, "le  " +(deces.date_deces).__str__())
    c.drawString(180,261, "............................................................................................................................")
    c.drawString(30,290, "Numéro de l'acte        à:      " +(deces.heure_deces).__str__()+"           à           "+(deces.lieu_deces).__str__())
    c.drawString(180,291, "............................................................................................................................")
    
    c.drawString(35,320,(deces.id).__str__()+ "                                                              "+(deces.personedeces).__str__())
    c.drawString(148,321, "......................................................................................................................................")
    
    c.drawString(148,350, "né le:   "+(deces.personedeces.date_naiss).__str__()+"   à:   "+(deces.personedeces.lieun).__str__())
    c.drawString(180,351, "............................................................................................................................")
    c.drawString(148,380, "Du sexe:   "+(deces.personedeces.sexe).__str__())
    c.drawString(180,381, "............................................................................................................................")
    
    c.drawString(148,410, "Fils de   "+(deces.personedeces.pere).__str__())
    c.drawString(180,411, "............................................................................................................................")
    
    c.drawString(148,440, "Et de   "+(deces.personedeces.mere).__str__())
    c.drawString(180,441, "............................................................................................................................")
    
    c.drawString(148,470, "Dressé le       "+datetime.datetime.now().strftime("%d/%m/%Y"))
    c.drawString(180,471, "............................................................................................................................")
    
    c.drawString(148,500, "sur la déclaration de  "+(deces.annonceur).__str__())
    c.drawString(340,501, ".............................................................................")
    
    c.drawString(148,530, "domicilié en cette commune, qui lecture faite a signé avec Nous")
    c.drawString(148,560, "Mentions mentionnées sur l'acte de deces")
    c.drawString(380,561, "................................................................")
    c.drawString(148,590, "......................................................................................................................................")
    
    
    c.drawString(370,650, "Fait à :   "+(deces.personedeces.BuretatCivile).__str__()+"   le:   "+datetime.datetime.now().strftime("%d/%m/%Y"))
    c.drawString(360,651, "............................................................")
    c.drawString(370,670, "L'officier de l'etat civil ")
    c.drawString(370,690, "signature et cachet")
    c.drawString(30, 750, "Réf:  EC.4")
    
    
    
    
    
    c.showPage()
    c.save()
    buf.seek(0)
    
        
   
    return FileResponse(buf, as_attachment=True, filename='extrait_de_deces.pdf')

    



def extrait_mariage(request, id):
     # Create Bytestream buffer
    buf = io.BytesIO()
    # Create a canvas 
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 10)

   
    # add line to texte 
    
    
    mariage = Mariage.objects.get(id=id)
    marie_info=Persone.objects.get(id=mariage.marie.id)
    mariee_info=Persone.objects.get(id=mariage.mariee.id)

    c.drawString(130, 40, "République Algérienne Démocratique et Populaire") 
    c.drawString(30, 70, "Ministère de l'Intérieur et des Collectivités Locales")
    c.drawString(30, 90, "Direction de l'Etat Civil")
    c.drawString(30, 110, "Willaya:   "+(marie_info.BuretatCivile.Commune.Daira.Wilaya).__str__()) 
    c.drawString(50,111, "............................................................")
    c.drawString(30, 130, "Daira:   "+(marie_info.BuretatCivile.Commune.Daira).__str__())
    c.drawString(50,131, "............................................................") 
    c.drawString(30, 150, "Commune:   "+(marie_info.BuretatCivile.Commune).__str__()) 
    c.drawString(50,151, "............................................................")
    c.drawString(30, 170, "Bureau:   "+(marie_info.BuretatCivile).__str__())
    c.drawString(50,171, "............................................................")
    c.drawString(240, 220, "ACTE DE MARIAGE")
    c.drawString(250,240,"[Copie intégrale(1)Extrait(2)]")

    c.drawString(148,260, "le  " +(mariage.date_mariage).__str__())
    c.drawString(180,261, "............................................................................................................................")
    c.drawString(30,280, "Numéro de l'acte        à:      " +(mariage.heure_mariage).__str__()+"       à la Communede :           "+(mariage.lieu_mariage).__str__())
    c.drawString(180,281, "............................................................................................................................")
    c.drawString(35,300,(mariage.id).__str__()+ "                               Daira:       "+(mariage.BuretatCivile.Commune.Daira).__str__()+"          Willaya de :    "+(mariage.BuretatCivile.Commune.Daira.Wilaya).__str__())
    c.drawString(180,301, "............................................................................................................................")
    c.drawString(148,320, 'Comparu devant Nous publiquement au siége de la Commune(4) :')
    c.drawString(180,321, "                                                                                                  ..........................")
    c.drawString(170,340, "Le nommé:   "+(mariage.marie).__str__())
    c.drawString(180,341, "............................................................................................................................")
    c.drawString(148,360, "Profession:   "+(mariage.profession_marie).__str__()+"         ne le:   "+(mariage.marie.date_naiss).__str__())
    c.drawString(180,361, "............................................................................................................................")
    c.drawString(148,380, "Fils de    :"+(marie_info.pere).__str__()+ "                   Et de      : "+(marie_info.mere).__str__() )
    c.drawString(180,381, "............................................................................................................................")
    
    c.drawString(170,410, "Et la Nommée:   "+(mariage.mariee).__str__())
    c.drawString(180,411, "............................................................................................................................")
    c.drawString(148,430, "Profession:   "+(mariage.profession_mariee).__str__()+"       ne le:   "+(mariage.mariee.date_naiss).__str__())
    c.drawString(180,431, "............................................................................................................................")
    c.drawString(148,450, "File de    "+(mariee_info.pere).__str__()+ "                  Et de "+(mariee_info.mere).__str__() )
    c.drawString(180,451, "............................................................................................................................")
    c.drawString(148,470, "Lesquels ont déclaré publiquement vouloir se prendre pour Epoux,et Nous avouns" )
    c.drawString(148,490, "prononcé au nom de la Loi qu'ils sont unis par le mariage en présence de:                    ")
    
    c.drawString(148,510, (mariage.temoine1).__str__() +"       Et de :                    "+(mariage.temoine2).__str__())
    c.drawString(180,511, "............................................................................................................................")

app1/templates/ajoudeces.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/Deces.css' %}">

<div class="main">

    <h1 id="titre"> Enregistrer Déces</h1>
    <img src="{% static 'images/Deces.svg' %}" id="logo3">
    <img src="{% static 'images/logo.svg' %}" id="logo2">
    <form method="post">
        {% csrf_token %}

        <div class="CONTENT">

            <div class="form-group">
                <label for="date-Deces">Date :</label>
                {{ form2.date_deces}}
            </div>

            <div class="form-group">
                <label for="Personne-Deces">Nom Prenom : </label>
                {{form2.personedeces}}
            </div>
            <div class=" form-group">
                <label for="Anonceur">Anonceur : </label>
                {{form2.annonceur}}
            </div>


            <div class="form-group">
                <label for="Huere-deces">Heure :</label>
                {{ form2.heure_deces}}
            </div>
            <div class="form-group">
                <label for="lieu-deces">Lieu : </label>
                {{ form2.lieu_deces }}
            </div>
            <div class="form-group">
                <label for="cause-deces">Cause Deces</label>
                {{ form2.cause_deces }}
            </div>
            <div>
                <button type="submit" name="submit">Submit </button>
            </div>
        </div>
    </form>

</div>


<!-- JS  -->
<script>
    document.querySelector("#id_date_deces").setAttribute("type", "date");
</script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!-- /JS-->

{% endblock %}

app1/templates/ajouterper.html
{% extends 'base.html' %}


{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/Personne.css' %}">

<div class="main">

    <h1 id="titre"> Enregistrer Naissance</h1>
    <form method="post">
        {% csrf_token %}
        <h3 id="sous-titre">Remplire le formulaire</h3>
        <div class="CONTENT">
            <div class="Personne">
                <div class=" form-group">
                    <label for="Nom">NOM : </label>
                    {{form.nom}}
                </div>
                <div class="form-group">
                    <label for="Prenom">Prenom </label>
                    {{ form.prenoms }}
                </div>
                <div class="form-group">
                    <label for="Sexe">Sexe </label>
                    {{ form.sexe}}
                </div>
                <div class="form-group">
                    <label for="DateN">Date Naissance </label>
                    {{ form.date_naiss }}
                </div>
                <div class="form-group">
                    <label for="H_naiss">Heure Naissance </label>
                    {{ form.heure_naiss }}
                </div>
                <div class="form-group">
                    <label for="Hopital">Lieu de Naissance </Label>
                    {{ form.lieun }}
                </div>
                <div class="form-group">
                    <label for="Bureau">Bureau etat civile </label>
                    {{ form.BuretatCivile }}
                </div>
            </div>
            <div class="Parent">
                <div class="form-group">
                    <label for="Pere ">Prenom du Pere </label>
                    {{ form.pere }}
                </div>
                <div class="form-group">
                    <label for="Grand_pere_paternel">Grand Pere </p>
                        {{ form.pere_pere }}
                </div>
                <div class="form-group">
                    <label for="mere">Nom et Prenom Mere </label>
                    {{ form.mere }}
                </div>
                <div class="form-group">
                    <label for="Pere_Mere"> Pere_Mere </label>
                    {{ form.pere_mere }}
                </div>
            </div>
            <div>
                <button type="submit" name="submit">Submit </button>
            </div>
            <img src="{% static 'images/logo.svg' %}" id="logo2">
        </div>
    </form>
    <img src="{% static 'images/bann.jpg' %}" id="banniere">

</div>
<!-- JS  -->
<script>
    document.querySelector("#id_date_naiss").setAttribute("type", "date");
</script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!-- /JS-->
{% endblock %}

app1/templates/edit.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/search.css' %}">


{% csrf_token %}
<div class="grille">
    <div class="elm-grid">
        <form method="post" action="">
            <h3> Update : </h3>
            {% csrf_token %}

            {{form.id}}
            <div class="form-group">
                <label> Nom :</label>
                {{form.nom}}
            </div>
            <div class="form-group">
                <label> Prenom :</label>
                {{form.prenoms}}
            </div>
            <div class="form-group">
                <label> Sexe :</label>
                {{form.sexe}}
            </div>
            <div class="form-group">
                <label> Date Naissance :</label>
                {{form.date_naiss}}
            </div>
            <div class="form-group">
                <label> Heure Naissance :</label>
                {{form.heure_naiss}}
            </div>
            <div class="form-group">
                <label> Pere :</label>
                {{form.pere}}
            </div>
            <div class="form-group">
                <label> Grand-pére :</label>
                {{form.pere_pere}}
            </div>
            <div class="form-group">
                <label> Mere :</label>
                {{form.mere}}
            </div>
            <div class="form-group">
                <label> Pere-Mere :</label>
                {{form.pere_mere }}
            </div>
            <div class="form-group">
                <label> Lieu Naissance :</label>
                {{form.lieun}}
            </div>
            <div class="form-group">
                <label> Bureau etat civil :</label>
                {{form.BuretatCivile}}
            </div>

            <div class="form-group">
                <br>
                <input type="submit" value="Update">

            </div>

        </form>
    </div>

</div>
<script>
    document.querySelector("#id_date_naiss").setAttribute("type", "date");
</script>
{% endblock %}

app1/templates/mariage.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/Mariage.css' %}">




<!-- /nav bar -->

<body>

    <div class="main">

        <h1 id="titre"> Enregistrer Mariage</h1>
        <img src="{% static 'images/mariage.svg' %}" id="logo3">
        <img src="{% static 'images/logo.svg' %}" id="logo2">
        <form method="post">
            {% csrf_token %}

            <div class="CONTENT">
                <div class="form-group">
                    <label for="requerant1">Nom Prenom Marie : </label>
                    {{form1.marie}}
                </div>

                <div class=" form-group">
                    <label for="proffesion_req1">Profession : </label>
                    {{form1.profession_marie}}
                </div>
                <div class="form-group">
                    <label for="requerant2">Nom et prenom Mariée </label>
                    {{ form1.mariee}}
                </div>
                <div class="form-group">
                    <label for="profession_req2">Profession : </label>
                    {{ form1.profession_mariee }}
                </div>
                <div class="form-group">
                    <label for="domicile_req2">Adresse Couple :</label>
                    {{ form1.domicile }}
                </div>
                <div class="form-group">
                    <label for="date_mariage">Date Mariage : </Label>
                    {{ form1.date_mariage }}
                </div>
                <div class="form-group">
                    <label for="heure_mariage">Heure : </label>
                    {{ form1.heure_mariage }}
                </div>

                <div class="form-group">
                    <label for="lieu_mariage">Lieu : </label>
                    {{ form1.lieu_mariage }}
                </div>
                <div class="form-group">
                    <label for="BuretatCivile">Bureau Etat Civile : </label>
                    {{ form1.BuretatCivile }}
                </div>
                <div class="form-group">
                    <label for="Temoin1">Temoin1: </label>
                    {{ form1.temoine1 }}
                </div>
                <div class="form-group">
                    <label for="temoin2">Temoin2 : </label>
                    {{ form1.temoine2 }}
                </div>

                <div>
                    <button type="submit" name="submit">Submit </button>
                </div>
            </div>
        </form>

    </div>


    <!-- JS  -->
    <script>
        document.querySelector("#id_date_mariage").setAttribute("type", "date");
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- /JS-->

    {% endblock %}

app1/templates/search.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'CSS/search.css' %}">
<div class="grille">
    <div class="elm-grid">
        <form action='' method="get">
            <h3> Rechercher Personne </h3>
            <div class="form-group">
                <label for="search"> Entrer le Nom :</label>
                <input type="text" name="nom" id="search">
            </div>
            <div class="form-group">
                <label for="search"> Entrer le Prenom : </label>
                <input type="text" name="prenoms" id="search">
            </div>
            <button type="submit">Recherche </button>
        </form>
    </div>
    <div class="elm-grid" id="result">

        <h4> Resultat : </h4>
        <ul class="info">
            {% for persones in data %}

            <li><label>ID :</label> {{persones.id}}</li>
            <li><label>Nom :</label> {{persones.nom}}</li>
            <li><label>Prenom :</label> {{persones.prenoms}}</li>
            <li><label>Sexe :</label> {{persones.sexe}}</li>
            <li><label>Date de Naissance :</label> {{persones.date_naiss}}</li>
            <li><label>Heure :</label> {{persones.heure_naiss}}</li>
            <li><label>Pére :</label> {{persones.pere}}</li>
            <li><label>Grand-pére :</label> {{persones.pere_pere}}</li>
            <li><label>Mere :</label> {{persones.mere}}</li>
            <li><label>Pére de la Mere :</label> {{persones.pere_mere }}</li>
            <li><label>Lieu de Naissance :</label> {{persones.lieun}}</li>
            <li><label>BuretatCivile:</label> {{persones.BuretatCivile}}</li>

            <a href="{% url 'extrait_pdf' persones.id %}" id="print">imprimer</a>
            <a href="{% url 'update' persones.id %}" id="update">modifier</a>

            {% if user.commune == persones.BuretatCivile.Commune %}
            <a href="{% url 'edit' persones.id %}">modifier</a>
            {% endif %}
            {% endfor %}
            <p> {{message}}</p>
        </ul>

    </div>
</div>

{% endblock %}

app1/templates/searchdeces.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'CSS/search.css' %}">
<div class="grille">
    <div class="elm-grid">
        <form action='' method="get">
            <h3> Rechercher Deces </h3>
            <div class="form-group">
                <label for="search"> Numéro d'acte de Deces </label>
                <input type="text" name="num_deces" id="search">
            </div>
            <button type="submit"> Recherche </button>
        </form>
    </div>



    <div class="elm-grid" id="result">
        <h4> Resultat: </h4>
        <ul class="info">

            {% for deces in data %}
            <li><label>Num Acte Deces :</label> {{deces.id}}</li>
            <li><label>Nom et Prenom :</label> {{deces.personedeces}}</li>
            <li><label>Annonceur :</label> {{deces.annonceur}}</li>
            <li><label>Date deces :</label> {{deces.date_deces}}</li>
            <li><label>Heure :</label> {{deces.heure_deces}}</li>
            <li><label>Lieu :</label> {{deces.lieu_deces}}</li>
            <li><label>Cause :</label> {{deces.cause_deces}}</li>

            <a href="{% url 'extrait_deces' deces.id %}" id="print">imprimer</a>







            {% endfor %}
            <p> {{message}}</p>
        </ul>
    </div>
</div>
{% endblock %}